FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS base
WORKDIR /app
EXPOSE 8080

FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src
COPY ["NotificationsAPI.csproj", "./"]
RUN dotnet restore "NotificationsAPI.csproj"
COPY . .
WORKDIR "/src/"
RUN dotnet build "NotificationsAPI.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "NotificationsAPI.csproj" -c Release -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "NotificationsAPI.dll"]
